project_id = "ecrxodmpqrdavqcpvdnl"

[functions.check-weather-alerts]
verify_jwt = false

[functions.generate-pdf]
verify_jwt = true

[functions.send-activity-reminders]
verify_jwt = false

[functions.send-email]
verify_jwt = true

[functions.entitlements]
verify_jwt = false

[functions.ai-usage-increment]
verify_jwt = true

[functions.ai-ask]
verify_jwt = false

[functions.activities-create]
verify_jwt = false

[functions.tasks-create]
verify_jwt = false

[functions.occurrences-create]
verify_jwt = false

[functions.transactions-create]
verify_jwt = false

[functions.pops-seed-minimal]
verify_jwt = false

[functions.ai-reset-today]
verify_jwt = false

[functions.admin-list-users]
verify_jwt = false
