INSERT INTO activity_types (code, display_name, category) VALUES
  ('plantio', 'Plantio', 'Implantação'),
  ('replantio', 'Replantio', 'Implantação'),
  ('preparo_solo', 'Preparo de Solo', 'Implantação'),
  ('calagem', 'Calagem', 'Implantação'),
  ('adubacao_base', 'Adubação de Base', 'Nutrição'),
  ('adubacao_cobertura', 'Adubação de Cobertura', 'Nutrição'),
  ('adubacao_foliar', 'Adubação Foliar', 'Nutrição'),
  ('fertirrigacao', 'Fertirrigação', 'Nutrição'),
  ('pulverizacao_herbicida', 'Pulverização — Herbicida', 'Proteção'),
  ('pulverizacao_fungicida', 'Pulverização — Fungicida', 'Proteção'),
  ('pulverizacao_inseticida', 'Pulverização — Inseticida', 'Proteção'),
  ('controle_biologico', 'Controle Biológico', 'Proteção'),
  ('manejo_pragas', 'Manejo de Pragas', 'Proteção'),
  ('irrigacao', 'Irrigação', 'Manejo'),
  ('capina', 'Capina / Roçada', 'Manejo'),
  ('poda', 'Poda', 'Manejo'),
  ('desbaste', 'Desbaste', 'Manejo'),
  ('monitoramento_campo', 'Monitoramento de Campo', 'Manejo'),
  ('colheita', 'Colheita', 'Colheita'),
  ('pos_colheita', 'Pós-Colheita / Secagem', 'Colheita'),
  ('transporte', 'Transporte', 'Colheita'),
  ('analise_solo', 'Análise de Solo', 'Diagnóstico'),
  ('analise_foliar', 'Análise Foliar', 'Diagnóstico'),
  ('manutencao_maquinas', 'Manutenção de Máquinas', 'Infraestrutura'),
  ('manutencao_infraestrutura', 'Manutenção de Infraestrutura', 'Infraestrutura'),
  ('outro', 'Outro', 'Outros')
ON CONFLICT (code) DO NOTHING;